import { lazy } from "react"
import {
  Binary,
  Braces,
  Calculator,
  Code2,
  Database,
  Diff,
  FileCode,
  FileCode2,
  FileText,
  Fingerprint,
  Globe,
  Hash,
  KeyRound,
  Link2,
  ListChecks,
  Lock,
  Minimize2,
  Network,
  Palette,
  Search,
  Shield,
  Tag,
  Terminal,
  Timer,
  Type,
} from "lucide-react"
import type { RegistryEntry } from "./types"

export const tools: RegistryEntry[] = [
  // ── Text & Comparison ─────────────────────────────────────────────────────
  {
    id: "diff-checker",
    name: "Text Diff Checker",
    description: "Compare two texts side-by-side with color highlights",
    category: "Text & Comparison",
    icon: Diff,
    component: lazy(() => import("../tools/diff-checker/DiffChecker")),
  },
  {
    id: "json-escaper",
    name: "JSON Escaper",
    description: "Escape and unescape JSON string values",
    category: "Text & Comparison",
    icon: Braces,
    component: lazy(() => import("../tools/json-escaper/JsonEscaper")),
  },

  // ── Encoding & Formatting ─────────────────────────────────────────────────
  {
    id: "html-xml-formatter",
    name: "HTML / XML Formatter",
    description: "Beautify or minify HTML and XML markup",
    category: "Encoding & Formatting",
    icon: FileCode2,
    component: lazy(() => import("../tools/html-xml-formatter/HtmlXmlFormatter")),
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format and validate JSON data",
    category: "Encoding & Formatting",
    icon: Code2,
    component: lazy(() => import("../tools/json-formatter/JsonFormatter")),
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Beautify and format SQL queries",
    category: "Encoding & Formatting",
    icon: Database,
    component: lazy(() => import("../tools/sql-formatter/SqlFormatter")),
  },
  {
    id: "yaml-json",
    name: "YAML ⇄ JSON",
    description: "Convert between YAML and JSON instantly",
    category: "Encoding & Formatting",
    icon: FileCode,
    component: lazy(() => import("../tools/yaml-json/YamlJson")),
  },

  // ── Cryptography & Security ───────────────────────────────────────────────
  {
    id: "jwt-debugger",
    name: "JWT Debugger",
    description: "Decode and inspect JSON Web Tokens",
    category: "Cryptography & Security",
    icon: Shield,
    component: lazy(() => import("../tools/jwt-debugger/JwtDebugger")),
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords",
    category: "Cryptography & Security",
    icon: Lock,
    component: lazy(() => import("../tools/password-generator/PasswordGenerator")),
  },
  {
    id: "rsa-generator",
    name: "RSA Key Generator",
    description: "Generate RSA key pairs in PEM format",
    category: "Cryptography & Security",
    icon: KeyRound,
    component: lazy(() => import("../tools/rsa-generator/RsaGenerator")),
  },

  // ── Development Tools ─────────────────────────────────────────────────────
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Live markdown editor with rendered preview",
    category: "Development Tools",
    icon: FileText,
    component: lazy(() => import("../tools/markdown-preview/MarkdownPreview")),
  },

  // ── Network & DevOps ──────────────────────────────────────────────────────
  {
    id: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Complete reference for all HTTP status codes",
    category: "Network & DevOps",
    icon: Globe,
    component: lazy(() => import("../tools/http-status-codes/HttpStatusCodes")),
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate IPv4 network addresses and host ranges",
    category: "Network & DevOps",
    icon: Network,
    component: lazy(() => import("../tools/subnet-calculator/SubnetCalculator")),
  },

  // ── DevOps & System Utilities ─────────────────────────────────────────────
  {
    id: "dotenv-validator",
    name: ".env Validator",
    description: "Validate and format dotenv configuration files",
    category: "DevOps & System Utilities",
    icon: ListChecks,
    component: lazy(() => import("../tools/dotenv-validator/DotenvValidator")),
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test patterns with real-time match highlighting",
    category: "DevOps & System Utilities",
    icon: Search,
    component: lazy(() => import("../tools/regex-tester/RegexTester")),
  },
  {
    id: "curl-converter",
    name: "cURL ⇄ JS Fetch Converter",
    description: "Convert curl commands to JavaScript fetch() code",
    category: "DevOps & System Utilities",
    icon: Terminal,
    component: lazy(() => import("../tools/curl-converter/CurlConverter")),
  },

  // ── Security & Web Utilities ──────────────────────────────────────────────
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    category: "Security & Web Utilities",
    icon: Hash,
    component: lazy(() => import("../tools/hash-generator/HashGenerator")),
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Bulk generate Version 4 UUIDs / GUIDs",
    category: "Security & Web Utilities",
    icon: Fingerprint,
    component: lazy(() => import("../tools/uuid-generator/UuidGenerator")),
  },
  {
    id: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities",
    category: "Security & Web Utilities",
    icon: Tag,
    component: lazy(() => import("../tools/html-entities/HtmlEntities")),
  },
  {
    id: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Percent-encode or decode URL strings",
    category: "Security & Web Utilities",
    icon: Link2,
    component: lazy(() => import("../tools/url-encoder/UrlEncoder")),
  },
  {
    id: "base64-converter",
    name: "Base64 Encoder / Decoder",
    description: "Encode and decode Base64 text and images",
    category: "Security & Web Utilities",
    icon: Binary,
    component: lazy(() => import("../tools/base64-converter/Base64Converter")),
  },

  // ── Text & Data Processors ────────────────────────────────────────────────
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text to camelCase, snake_case, kebab-case, and more",
    category: "Text & Data Processors",
    icon: Type,
    component: lazy(() => import("../tools/case-converter/CaseConverter")),
  },
  {
    id: "text-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, lines, and bytes in real-time",
    category: "Text & Data Processors",
    icon: Calculator,
    component: lazy(() => import("../tools/text-counter/TextCounter")),
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert hex colors to RGB, RGBA, and HSL",
    category: "Text & Data Processors",
    icon: Palette,
    component: lazy(() => import("../tools/color-converter/ColorConverter")),
  },
  {
    id: "json-minifier",
    name: "JSON Minifier",
    description: "Minify or beautify JSON with size savings stats",
    category: "Text & Data Processors",
    icon: Minimize2,
    component: lazy(() => import("../tools/json-minifier/JsonMinifier")),
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to dates and back",
    category: "Text & Data Processors",
    icon: Timer,
    component: lazy(() => import("../tools/timestamp-converter/TimestampConverter")),
  },
]
