import { lazy } from "react"
import {
  AlertOctagon,
  Bookmark,
  BookOpen,
  CalendarDays,
  CalendarPlus,
  Dice5,
  Gauge,
  GitCompareArrows,
  Globe2,
  GraduationCap,
  HelpCircle,
  Library,
  ListChecks,
  Repeat,
  Rewind,
  ShieldCheck,
  SlidersHorizontal,
  Sparkle,
  Sparkles,
  Timer,
} from "lucide-react"
import type { RegistryEntry } from "./types"

export const tools: RegistryEntry[] = [
  // ── Cron Tools ─────────────────────────────────────────────────────────────
  {
    id: "cheat-sheet",
    name: "Cron Cheat Sheet",
    description: "Quick reference for cron syntax, special characters, and shortcuts",
    category: "Cron Tools",
    icon: BookOpen,
    component: lazy(() => import("../tools/cheat-sheet/CheatSheet")),
  },
  {
    id: "examples",
    name: "Cron Examples Library",
    description: "Browse and search common cron expression examples",
    category: "Cron Tools",
    icon: Library,
    component: lazy(() => import("../tools/examples/ExamplesLibrary")),
  },
  {
    id: "validator",
    name: "Cron Validator",
    description: "Validate a cron expression field-by-field and normalize it",
    category: "Cron Tools",
    icon: ShieldCheck,
    component: lazy(() => import("../tools/cron-validator/CronValidator")),
  },
  {
    id: "generator",
    name: "Cron Generator",
    description: "Describe a schedule in plain English, get the cron expression",
    category: "Cron Tools",
    icon: Sparkles,
    component: lazy(() => import("../tools/cron-generator/CronGenerator")),
  },
  {
    id: "visual-builder",
    name: "Visual Cron Builder",
    description: "Build a cron expression field by field with a live preview",
    category: "Cron Tools",
    icon: SlidersHorizontal,
    component: lazy(() => import("../tools/visual-builder/VisualBuilder")),
  },
  {
    id: "timezone-converter",
    name: "Cron Timezone Converter",
    description: "Convert a cron schedule's time from one timezone to another",
    category: "Cron Tools",
    icon: Globe2,
    component: lazy(() => import("../tools/timezone-converter/TimezoneConverter")),
  },
  {
    id: "frequency-calculator",
    name: "Cron Frequency Calculator",
    description: "See how many times a cron expression runs per day, week, month, year",
    category: "Cron Tools",
    icon: Gauge,
    component: lazy(() => import("../tools/frequency-calculator/FrequencyCalculator")),
  },
  {
    id: "visualizer",
    name: "Schedule Visualizer",
    description: "See a cron schedule on a calendar or as a 100-run timeline",
    category: "Cron Tools",
    icon: CalendarDays,
    component: lazy(() => import("../tools/schedule-visualizer/ScheduleVisualizer")),
  },
  {
    id: "compare",
    name: "Compare Expressions",
    description: "Check whether two cron expressions produce the same schedule",
    category: "Cron Tools",
    icon: GitCompareArrows,
    component: lazy(() => import("../tools/compare/CompareExpressions")),
  },
  {
    id: "learn",
    name: "Cron Learning Center",
    description: "What is cron, cron vs crontab, syntax, best practices, and common mistakes",
    category: "Cron Tools",
    icon: GraduationCap,
    component: lazy(() => import("../tools/learn/LearningCenter")),
  },
  {
    id: "countdown",
    name: "Next Run Countdown",
    description: "A live, ticking countdown until a cron expression's next execution",
    category: "Cron Tools",
    icon: Timer,
    component: lazy(() => import("../tools/countdown/Countdown")),
  },
  {
    id: "previous-run",
    name: "Previous Run Calculator",
    description: "Find out when a cron expression last ran",
    category: "Cron Tools",
    icon: Rewind,
    component: lazy(() => import("../tools/previous-run/PreviousRun")),
  },
  {
    id: "randomizer",
    name: "Cron Randomizer",
    description: "Generate random, valid cron expressions for testing",
    category: "Cron Tools",
    icon: Dice5,
    component: lazy(() => import("../tools/randomizer/Randomizer")),
  },
  {
    id: "conflict-detector",
    name: "Cron Conflict Detector",
    description: "Check whether multiple cron jobs execute at the same time",
    category: "Cron Tools",
    icon: AlertOctagon,
    component: lazy(() => import("../tools/conflict-detector/ConflictDetector")),
  },
  {
    id: "optimizer",
    name: "Cron Schedule Optimizer",
    description: "Simplify a verbose cron expression into cleaner equivalent syntax",
    category: "Cron Tools",
    icon: Sparkle,
    component: lazy(() => import("../tools/optimizer/Optimizer")),
  },
  {
    id: "format-converter",
    name: "Quartz ⇄ Standard Converter",
    description: "Convert between standard, Quartz, and AWS EventBridge cron formats",
    category: "Cron Tools",
    icon: Repeat,
    component: lazy(() => import("../tools/format-converter/FormatConverter")),
  },
  {
    id: "favorites",
    name: "Favorites Manager",
    description: "Organize saved cron expressions with categories, notes, and export",
    category: "Cron Tools",
    icon: Bookmark,
    component: lazy(() => import("../tools/favorites/FavoritesManager")),
  },
  {
    id: "interview-questions",
    name: "Cron Interview Questions",
    description: "18 interview questions and answers, Beginner to Advanced",
    category: "Cron Tools",
    icon: HelpCircle,
    component: lazy(() => import("../tools/interview-questions/InterviewQuestions")),
  },
  {
    id: "batch-validator",
    name: "Batch Crontab Validator",
    description: "Validate every line of a full crontab file at once",
    category: "Cron Tools",
    icon: ListChecks,
    component: lazy(() => import("../tools/batch-validator/BatchValidator")),
  },
  {
    id: "ical-export",
    name: "Cron to iCal Export",
    description: "Export a cron schedule's upcoming runs as a downloadable calendar file",
    category: "Cron Tools",
    icon: CalendarPlus,
    component: lazy(() => import("../tools/ical-export/IcalExport")),
  },
]
